/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.main.container.content;

import com.functions.DB;
import java.awt.Dimension;
import javax.swing.BorderFactory;

/**
 *
 * @author mrmango
 */
public class ProductsMain extends javax.swing.JPanel {

    /**
     * Creates new form AdminSupplierMain
     */
    String sql = "select P.idProduct, P.idSupplier, P.productName, P.stock, P.price, P.pvp, P.discount, C.description, C.name "
            + "from products P join categories C on P.idCategory=C.idCategory";

    public ProductsMain(boolean admin) {
        initComponents();
        if (!admin) {
        }
        DB.showQueryInTable(tblProducts, sql);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        pnlSearch = new javax.swing.JPanel();
        searchID = new javax.swing.JLabel();
        search_icon = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();

        setBackground(new java.awt.Color(236, 239, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContent.setBackground(new java.awt.Color(229, 233, 240));
        pnlContent.setPreferredSize(new java.awt.Dimension(740, 370));
        pnlContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProducts.setAutoCreateRowSorter(true);
        tblProducts.setBackground(new java.awt.Color(229, 233, 240));
        tblProducts.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        tblProducts.setForeground(new java.awt.Color(67, 76, 94));
        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Prov", "Nombre", "Stock", "Precio", "PvP", "Desc %", "Descripction", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProducts.setFocusable(false);
        tblProducts.setGridColor(new java.awt.Color(236, 239, 244));
        tblProducts.setRowHeight(35);
        tblProducts.setSelectionBackground(new java.awt.Color(235, 203, 139));
        tblProducts.getTableHeader().setReorderingAllowed(false);
        tblProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProducts);
        if (tblProducts.getColumnModel().getColumnCount() > 0) {
            tblProducts.getColumnModel().getColumn(0).setMaxWidth(35);
            tblProducts.getColumnModel().getColumn(1).setMaxWidth(40);
            tblProducts.getColumnModel().getColumn(2).setMinWidth(80);
            tblProducts.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblProducts.getColumnModel().getColumn(2).setMaxWidth(150);
            tblProducts.getColumnModel().getColumn(3).setMaxWidth(50);
            tblProducts.getColumnModel().getColumn(4).setMaxWidth(50);
            tblProducts.getColumnModel().getColumn(5).setMaxWidth(50);
            tblProducts.getColumnModel().getColumn(6).setMaxWidth(50);
            tblProducts.getColumnModel().getColumn(8).setMinWidth(80);
            tblProducts.getColumnModel().getColumn(8).setPreferredWidth(100);
            tblProducts.getColumnModel().getColumn(8).setMaxWidth(125);
        }
        tblProducts.getTableHeader().setOpaque(false);
        tblProducts.getTableHeader().setBackground(new java.awt.Color(229, 233, 240));
        tblProducts.getTableHeader().setForeground(new java.awt.Color(46,52,64));
        tblProducts.getTableHeader().setFont(new java.awt.Font("Roboto", 1, 14));

        pnlContent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 800, 420));
        jScrollPane1.setBorder(BorderFactory.createEmptyBorder());
        jScrollPane1.getVerticalScrollBar().setPreferredSize( new Dimension(0,0) );

        add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 440));

        pnlSearch.setBackground(new java.awt.Color(136, 192, 208));
        pnlSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchID.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        searchID.setForeground(new java.awt.Color(59, 66, 82));
        searchID.setText("ID");
        pnlSearch.add(searchID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, 20, 20));

        search_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        pnlSearch.add(search_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 8, 30, 20));

        txtSearch.setBackground(new java.awt.Color(136, 192, 208));
        txtSearch.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(46, 52, 64));
        txtSearch.setBorder(null);
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        pnlSearch.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 8, 100, 20));

        add(pnlSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 462, -1, 35));
    }// </editor-fold>//GEN-END:initComponents

    private void tblProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductsMouseClicked

    }//GEN-LAST:event_tblProductsMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String query = txtSearch.getText();
        DB.tableSorter(tblProducts, query);
    }//GEN-LAST:event_txtSearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JLabel searchID;
    private javax.swing.JLabel search_icon;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
