/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.main.container.content;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author mrmango
 */
public class SalesBill extends javax.swing.JPanel {

    /**
     * Creates new form AdminSuppliersAddProducts
     */
    public SalesBill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBill = new javax.swing.JTable();
        lblDate = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblNui = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtCustomer = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtNui = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtTotalPrice = new javax.swing.JTextField();
        btnPrint = new javax.swing.JButton();
        btnPrint1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(236, 239, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContent.setBackground(new java.awt.Color(236, 239, 244));
        pnlContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblBill.setBackground(new java.awt.Color(229, 233, 240));
        tblBill.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        tblBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Descripción", "Precio Unitario", "IVA", "Descuento", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBill.setShowGrid(true);
        tblBill.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblBill);
        tblBill.getTableHeader().setOpaque(false);
        tblBill.getTableHeader().setBackground(new java.awt.Color(94,129,172));
        tblBill.getTableHeader().setFont(new java.awt.Font("Roboto Medium", 0, 14));

        pnlContent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 840, 310));
        jScrollPane1.getVerticalScrollBar().setPreferredSize( new Dimension(0,0) );

        lblDate.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        lblDate.setForeground(new java.awt.Color(59, 66, 82));
        lblDate.setText("Fecha: ");
        pnlContent.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblCustomer.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        lblCustomer.setForeground(new java.awt.Color(59, 66, 82));
        lblCustomer.setText("Cliente: ");
        pnlContent.add(lblCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        lblAddress.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(59, 66, 82));
        lblAddress.setText("Dirección: ");
        pnlContent.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        lblNui.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        lblNui.setForeground(new java.awt.Color(59, 66, 82));
        lblNui.setText("RUC/NUI: ");
        pnlContent.add(lblNui, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        lblPhone.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(59, 66, 82));
        lblPhone.setText("Teléfono: ");
        pnlContent.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, -1));

        lblTotalPrice.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        lblTotalPrice.setForeground(new java.awt.Color(59, 66, 82));
        lblTotalPrice.setText("TOTAL:");
        pnlContent.add(lblTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, -1, -1));

        txtDate.setEditable(false);
        txtDate.setBackground(new java.awt.Color(236, 239, 244));
        txtDate.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtDate.setBorder(null);
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        pnlContent.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 190, 22));

        txtCustomer.setEditable(false);
        txtCustomer.setBackground(new java.awt.Color(236, 239, 244));
        txtCustomer.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtCustomer.setBorder(null);
        txtCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerActionPerformed(evt);
            }
        });
        pnlContent.add(txtCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 190, 22));

        txtAddress.setEditable(false);
        txtAddress.setBackground(new java.awt.Color(236, 239, 244));
        txtAddress.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtAddress.setBorder(null);
        pnlContent.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 190, 22));

        txtNui.setEditable(false);
        txtNui.setBackground(new java.awt.Color(236, 239, 244));
        txtNui.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtNui.setBorder(null);
        pnlContent.add(txtNui, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 190, 22));

        txtPhone.setEditable(false);
        txtPhone.setBackground(new java.awt.Color(236, 239, 244));
        txtPhone.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtPhone.setBorder(null);
        pnlContent.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 190, 22));

        txtTotalPrice.setEditable(false);
        txtTotalPrice.setBackground(new java.awt.Color(236, 239, 244));
        txtTotalPrice.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtTotalPrice.setBorder(null);
        txtTotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPriceActionPerformed(evt);
            }
        });
        pnlContent.add(txtTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 120, 22));

        add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 450));

        btnPrint.setBackground(new java.awt.Color(180, 142, 173));
        btnPrint.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(67, 76, 94));
        btnPrint.setText("IMPRIMIR");
        btnPrint.setBorder(null);
        btnPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrintMouseClicked(evt);
            }
        });
        add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 120, 40));

        btnPrint1.setBackground(new java.awt.Color(180, 142, 173));
        btnPrint1.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btnPrint1.setForeground(new java.awt.Color(67, 76, 94));
        btnPrint1.setText("IMPRIMIR");
        btnPrint1.setBorder(null);
        btnPrint1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrint1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrint1MouseClicked(evt);
            }
        });
        add(btnPrint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtTotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPriceActionPerformed

    private void btnPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseClicked
        JOptionPane.showMessageDialog(null, "Funcion en desarrollo");
    }//GEN-LAST:event_btnPrintMouseClicked

    private void btnPrint1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrint1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrint1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnPrint1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblNui;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JTable tblBill;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCustomer;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtNui;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables
}
