/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.main.container.content;

import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author mrmango
 */
public class SellMain extends javax.swing.JPanel {

    /**
     * Creates new form AdminSuppliersAddProducts
     */
    public SellMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBill = new javax.swing.JTable();
        lblCustomer = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        txtNui = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtPhone1 = new javax.swing.JTextField();
        pnlSearch4 = new javax.swing.JPanel();
        txtFldSearch4 = new javax.swing.JTextField();
        searchID = new javax.swing.JLabel();
        search_icon = new javax.swing.JLabel();
        btnCF = new javax.swing.JButton();
        btnBill = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(236, 239, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContent.setBackground(new java.awt.Color(236, 239, 244));
        pnlContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblBill.setBackground(new java.awt.Color(229, 233, 240));
        tblBill.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        tblBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripcion", "Cant.", "Precio U.", "IVA", "Dsc", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBill.setShowGrid(true);
        tblBill.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblBill);
        tblBill.getTableHeader().setOpaque(false);
        tblBill.getTableHeader().setBackground(new java.awt.Color(94,129,172));
        tblBill.getTableHeader().setFont(new java.awt.Font("Roboto Medium", 0, 14));
        if (tblBill.getColumnModel().getColumnCount() > 0) {
            tblBill.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblBill.getColumnModel().getColumn(0).setMaxWidth(60);
            tblBill.getColumnModel().getColumn(1).setPreferredWidth(125);
            tblBill.getColumnModel().getColumn(1).setMaxWidth(160);
            tblBill.getColumnModel().getColumn(3).setPreferredWidth(60);
            tblBill.getColumnModel().getColumn(3).setMaxWidth(100);
            tblBill.getColumnModel().getColumn(4).setPreferredWidth(60);
            tblBill.getColumnModel().getColumn(4).setMaxWidth(100);
            tblBill.getColumnModel().getColumn(5).setPreferredWidth(40);
            tblBill.getColumnModel().getColumn(5).setMaxWidth(50);
            tblBill.getColumnModel().getColumn(6).setPreferredWidth(40);
            tblBill.getColumnModel().getColumn(6).setMaxWidth(60);
            tblBill.getColumnModel().getColumn(7).setPreferredWidth(75);
            tblBill.getColumnModel().getColumn(7).setMaxWidth(150);
        }

        pnlContent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 840, 360));
        jScrollPane1.setBorder(BorderFactory.createEmptyBorder());
        jScrollPane1.getVerticalScrollBar().setPreferredSize( new Dimension(0,0) );

        lblCustomer.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        lblCustomer.setForeground(new java.awt.Color(59, 66, 82));
        lblCustomer.setText("ID");
        pnlContent.add(lblCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        lblPhone.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(59, 66, 82));
        lblPhone.setText("Cantidad");
        pnlContent.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        lblTotalPrice.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        lblTotalPrice.setForeground(new java.awt.Color(59, 66, 82));
        lblTotalPrice.setText("TOTAL:");
        pnlContent.add(lblTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 425, -1, 22));

        txtNui.setBackground(new java.awt.Color(236, 239, 244));
        txtNui.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtNui.setBorder(null);
        pnlContent.add(txtNui, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 425, 110, 22));

        txtPhone.setEditable(false);
        txtPhone.setBackground(new java.awt.Color(136, 192, 208));
        txtPhone.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtPhone.setBorder(null);
        pnlContent.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 50, 22));

        txtPhone1.setEditable(false);
        txtPhone1.setBackground(new java.awt.Color(136, 192, 208));
        txtPhone1.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtPhone1.setBorder(null);
        pnlContent.add(txtPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 22));

        pnlSearch4.setBackground(new java.awt.Color(136, 192, 208));
        pnlSearch4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFldSearch4.setBackground(new java.awt.Color(136, 192, 208));
        txtFldSearch4.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        txtFldSearch4.setBorder(null);
        txtFldSearch4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldSearch4ActionPerformed(evt);
            }
        });
        pnlSearch4.add(txtFldSearch4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 8, 120, 20));

        searchID.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        searchID.setForeground(new java.awt.Color(59, 66, 82));
        searchID.setText("Nombre");
        pnlSearch4.add(searchID, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 8, -1, 20));

        search_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        pnlSearch4.add(search_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 8, 30, 20));

        pnlContent.add(pnlSearch4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 230, 35));

        add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 450));

        btnCF.setBackground(new java.awt.Color(208, 135, 112));
        btnCF.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btnCF.setForeground(new java.awt.Color(67, 76, 94));
        btnCF.setText("CONSUMIDOR F.");
        btnCF.setBorder(null);
        btnCF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCFMouseClicked(evt);
            }
        });
        add(btnCF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 120, 40));

        btnBill.setBackground(new java.awt.Color(143, 188, 187));
        btnBill.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btnBill.setForeground(new java.awt.Color(67, 76, 94));
        btnBill.setText("IMPRIMIR");
        btnBill.setBorder(null);
        btnBill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBillMouseClicked(evt);
            }
        });
        add(btnBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 120, 40));

        btnCancel.setBackground(new java.awt.Color(191, 97, 106));
        btnCancel.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(67, 76, 94));
        btnCancel.setText("CANCELAR");
        btnCancel.setBorder(null);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCFMouseClicked
        JOptionPane.showMessageDialog(null, "Funcion en desarrollo");
    }//GEN-LAST:event_btnCFMouseClicked

    private void btnBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBillMouseClicked
        JOptionPane.showMessageDialog(null, "Funcion en desarrollo");
    }//GEN-LAST:event_btnBillMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelMouseClicked

    private void txtFldSearch4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldSearch4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldSearch4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBill;
    private javax.swing.JButton btnCF;
    private javax.swing.JButton btnCancel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JPanel pnlSearch1;
    private javax.swing.JPanel pnlSearch2;
    private javax.swing.JPanel pnlSearch4;
    private javax.swing.JLabel searchID;
    private javax.swing.JLabel search_icon;
    private javax.swing.JTable tblBill;
    private javax.swing.JTextField txtFldSearch;
    private javax.swing.JTextField txtFldSearch1;
    private javax.swing.JTextField txtFldSearch2;
    private javax.swing.JTextField txtFldSearch4;
    private javax.swing.JTextField txtNui;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPhone1;
    // End of variables declaration//GEN-END:variables
}
