/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.main.frame;
import com.logic.model.Person;
import com.main.container.DashboardPanel;
import com.main.container.CustomerPanel;
import com.main.container.SettingsPanel;
import com.main.container.SalesPanel;
import com.main.container.ProductsPanel;
import com.main.container.SellPanel;
import com.logic.main.Design;

import javax.swing.*;


/**
 *
 * @author mrmango
 */
public class EmployeeFrame extends javax.swing.JFrame {

    Person person;
    JPanel btnActive;
    int xx, yy;

    public EmployeeFrame(Person employee) {
        person = employee;
        initComponents();
        customInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        pnlUserMenu = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnSettings = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        pnlStatus = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        userMenu = new javax.swing.JButton();
        pnlMenu = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSell = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnProducts = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnCustomers = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnSales = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 625));
        setUndecorated(true);

        background.setBackground(new java.awt.Color(236, 239, 244));
        background.setMaximumSize(new java.awt.Dimension(1000, 625));
        background.setMinimumSize(new java.awt.Dimension(1000, 625));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUserMenu.setBackground(new java.awt.Color(129, 161, 193));
        pnlUserMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setBackground(new java.awt.Color(191, 97, 106));
        btnLogout.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(76, 86, 106));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        btnLogout.setText("LOGOUT");
        btnLogout.setBorder(null);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        pnlUserMenu.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 90, 30));

        btnSettings.setBackground(new java.awt.Color(143, 188, 187));
        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settings.png"))); // NOI18N
        btnSettings.setBorder(null);
        btnSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSettings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSettingsMouseClicked(evt);
            }
        });
        pnlUserMenu.add(btnSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 30, 30));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(67, 76, 94));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EMPLEADO");
        pnlUserMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, -1));

        jProgressBar1.setBackground(new java.awt.Color(129, 161, 193));
        jProgressBar1.setForeground(new java.awt.Color(143, 188, 187));
        pnlUserMenu.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 20));

        background.add(pnlUserMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 150, 0));

        pnlStatus.setBackground(new java.awt.Color(94, 129, 172));
        pnlStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        pnlStatus.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlStatusMouseDragged(evt);
            }
        });
        pnlStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlStatusMousePressed(evt);
            }
        });
        pnlStatus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/littleStore.png"))); // NOI18N
        title.setText("MINIMARKET QMET");
        pnlStatus.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 0, 210, 40));

        btnMenu.setBackground(new java.awt.Color(94, 129, 172));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu.png"))); // NOI18N
        btnMenu.setBorder(null);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        pnlStatus.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        btnMinimize.setBackground(new java.awt.Color(180, 142, 173));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimize.png"))); // NOI18N
        btnMinimize.setBorder(null);
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });
        pnlStatus.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 40, 40));

        btnClose.setBackground(new java.awt.Color(208, 135, 112));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        pnlStatus.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 40, 40));

        userMenu.setBackground(new java.awt.Color(94, 129, 172));
        userMenu.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        userMenu.setForeground(new java.awt.Color(67, 76, 94));
        userMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        userMenu.setText("EMPLEADO");
        userMenu.setBorder(null);
        userMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMenuMouseClicked(evt);
            }
        });
        pnlStatus.add(userMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 150, 40));

        background.add(pnlStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 40));

        pnlMenu.setBackground(new java.awt.Color(216, 222, 233));
        pnlMenu.setMaximumSize(new java.awt.Dimension(210, 585));
        pnlMenu.setMinimumSize(new java.awt.Dimension(60, 585));
        pnlMenu.setPreferredSize(new java.awt.Dimension(60, 585));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDashboard.setBackground(new java.awt.Color(216, 222, 233));
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashboardMouseExited(evt);
            }
        });
        btnDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.png"))); // NOI18N
        btnDashboard.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 45));

        jLabel7.setBackground(new java.awt.Color(76, 86, 106));
        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(76, 86, 106));
        jLabel7.setText("Dashboard");
        btnDashboard.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 100, 45));

        pnlMenu.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 162, 210, 45));

        btnSell.setBackground(new java.awt.Color(216, 222, 233));
        btnSell.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSellMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSellMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSellMouseExited(evt);
            }
        });
        btnSell.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sell.png"))); // NOI18N
        btnSell.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 45));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(76, 86, 106));
        jLabel5.setText("Vender");
        btnSell.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 100, 45));

        pnlMenu.add(btnSell, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 207, 210, 45));

        btnProducts.setBackground(new java.awt.Color(216, 222, 233));
        btnProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProductsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProductsMouseExited(evt);
            }
        });
        btnProducts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/products.png"))); // NOI18N
        btnProducts.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 45));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(76, 86, 106));
        jLabel11.setText("Productos");
        btnProducts.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 100, 45));

        pnlMenu.add(btnProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 252, 210, 45));

        btnCustomers.setBackground(new java.awt.Color(216, 222, 233));
        btnCustomers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCustomersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCustomersMouseExited(evt);
            }
        });
        btnCustomers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer.png"))); // NOI18N
        btnCustomers.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 45));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(76, 86, 106));
        jLabel13.setText("Clientes");
        btnCustomers.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 100, 45));

        pnlMenu.add(btnCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 297, 210, 45));

        btnSales.setBackground(new java.awt.Color(216, 222, 233));
        btnSales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalesMouseExited(evt);
            }
        });
        btnSales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopping_car_filled.png"))); // NOI18N
        btnSales.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 45));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(76, 86, 106));
        jLabel9.setText("Ventas");
        btnSales.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 100, 45));

        pnlMenu.add(btnSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 342, 210, 45));

        background.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 60, 590));

        pnlMain.setBackground(new java.awt.Color(236, 239, 244));
        pnlMain.setLayout(new javax.swing.BoxLayout(pnlMain, javax.swing.BoxLayout.LINE_AXIS));
        background.add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 940, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseEntered
        Design.optionsColor(btnDashboard);
    }//GEN-LAST:event_btnDashboardMouseEntered

    private void btnDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseExited
        Design.resetColor(btnDashboard);
    }//GEN-LAST:event_btnDashboardMouseExited

    private void btnSellMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSellMouseEntered
        Design.optionsColor(btnSell);
    }//GEN-LAST:event_btnSellMouseEntered

    private void btnSellMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSellMouseExited
        Design.resetColor(btnSell);
    }//GEN-LAST:event_btnSellMouseExited

    private void btnSalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesMouseEntered
        Design.optionsColor(btnSales);
    }//GEN-LAST:event_btnSalesMouseEntered

    private void btnSalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesMouseExited
        Design.resetColor(btnSales);
    }//GEN-LAST:event_btnSalesMouseExited

    private void btnCustomersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomersMouseEntered
        Design.optionsColor(btnCustomers);
    }//GEN-LAST:event_btnCustomersMouseEntered

    private void btnCustomersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomersMouseExited
        Design.resetColor(btnCustomers);
    }//GEN-LAST:event_btnCustomersMouseExited

    private void btnProductsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductsMouseEntered
        Design.optionsColor(btnProducts);
    }//GEN-LAST:event_btnProductsMouseEntered

    private void btnProductsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductsMouseExited
        Design.resetColor(btnProducts);
    }//GEN-LAST:event_btnProductsMouseExited

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked
        if (!(btnActive == btnDashboard)) {
            Design.clickOptions(btnDashboard, btnActive, pnlMain, new DashboardPanel());
        }
        if (pnlMenu.getWidth() == 210) {
            Design.menuAnimation(pnlMenu);
        }
        if (pnlUserMenu.getHeight() == 137) {
            Design.menuAnimation(pnlUserMenu);
        }
        btnActive = btnDashboard;
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void btnSellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSellMouseClicked
        if (!(btnActive == btnSell)) {
            Design.clickOptions(btnSell, btnActive, pnlMain, new SellPanel(person));
        }
        if (pnlMenu.getWidth() == 210) {
            Design.menuAnimation(pnlMenu);
        }
        if (pnlUserMenu.getHeight() == 137) {
            Design.menuAnimation(pnlUserMenu);
        }
        btnActive = btnSell;
    }//GEN-LAST:event_btnSellMouseClicked

    private void btnSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesMouseClicked
        if (!(btnActive == btnSales)) {
            Design.clickOptions(btnSales, btnActive, pnlMain, new SalesPanel(false));
        }
        if (pnlMenu.getWidth() == 210) {
            Design.menuAnimation(pnlMenu);
        }
        if (pnlUserMenu.getHeight() == 137) {
            Design.menuAnimation(pnlUserMenu);
        }
        btnActive = btnSales;
    }//GEN-LAST:event_btnSalesMouseClicked

    private void btnCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomersMouseClicked
        if (!(btnActive == btnCustomers)) {
            Design.clickOptions(btnCustomers, btnActive, pnlMain, new CustomerPanel(false));
        }
        if (pnlMenu.getWidth() == 210) {
            Design.menuAnimation(pnlMenu);
        }
        if (pnlUserMenu.getHeight() == 137) {
            Design.menuAnimation(pnlUserMenu);
        }
        btnActive = btnCustomers;
    }//GEN-LAST:event_btnCustomersMouseClicked

    private void btnProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductsMouseClicked
        if (!(btnActive == btnProducts)) {
            Design.clickOptions(btnProducts, btnActive, pnlMain, new ProductsPanel(false));
        }
        if (pnlMenu.getWidth() == 210) {
            Design.menuAnimation(pnlMenu);
        }
        if (pnlUserMenu.getHeight() == 137) {
            Design.menuAnimation(pnlUserMenu);
        }
        btnActive = btnProducts;
    }//GEN-LAST:event_btnProductsMouseClicked

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        Design.menuAnimation(pnlMenu);
        if (pnlUserMenu.getHeight() == 137) {
            Design.menuAnimation(pnlUserMenu);
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void pnlStatusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlStatusMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_pnlStatusMousePressed

    private void pnlStatusMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlStatusMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_pnlStatusMouseDragged

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Login login = new Login();
        login.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void userMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMenuMouseClicked
        Design.menuAnimation(pnlUserMenu);
    }//GEN-LAST:event_userMenuMouseClicked

    private void btnSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingsMouseClicked
        Design.panelChange(pnlMain, new SettingsPanel(person));
    }

    public void setUserName(Person ps){
        userMenu.setText(ps.getFirstName()+" "+ps.getLastName());
    }

    public void customInitComponents(){
        setResizable(false);
        setLocationRelativeTo(null);
        btnActive = btnDashboard;
        Design.clickOptions(btnDashboard, btnActive, pnlMain, new DashboardPanel());
        userMenu.setText(person.getFirstName()+" "+person.getLastName());
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnClose;
    private javax.swing.JPanel btnCustomers;
    private javax.swing.JPanel btnDashboard;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JPanel btnProducts;
    private javax.swing.JPanel btnSales;
    private javax.swing.JPanel btnSell;
    private javax.swing.JButton btnSettings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlStatus;
    private javax.swing.JPanel pnlUserMenu;
    private javax.swing.JLabel title;
    private javax.swing.JButton userMenu;
    // End of variables declaration//GEN-END:variables
}
