/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.main.container;
import com.main.container.content.CustomersAdd;
import com.main.container.content.CustomersMain;
import com.functions.Design;
/**
 *
 * @author mrmango
 */
public class Customers extends javax.swing.JPanel {

    /**
     * Creates new form AdminEmployeeMain
     */
    boolean admin;
    public Customers(boolean admin) {
        initComponents();
        this.admin = admin;
        if(!admin){
            btnAddCustomers.setVisible(false);
        }
        Design.panelChange(pnlContent, new CustomersMain(admin));
        btnBack.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnAddCustomers = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 239, 244));
        setPreferredSize(new java.awt.Dimension(940, 590));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContent.setBackground(new java.awt.Color(236, 239, 244));
        pnlContent.setPreferredSize(new java.awt.Dimension(840, 500));
        pnlContent.setLayout(new javax.swing.BoxLayout(pnlContent, javax.swing.BoxLayout.LINE_AXIS));
        add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 840, 500));

        lblTitle.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(46, 52, 64));
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer.png"))); // NOI18N
        lblTitle.setText("CLIENTES");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 120, 30));

        btnAddCustomers.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnAddCustomers.setForeground(new java.awt.Color(46, 52, 64));
        btnAddCustomers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_person.png"))); // NOI18N
        btnAddCustomers.setText("Cliente");
        btnAddCustomers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddCustomersMouseClicked(evt);
            }
        });
        add(btnAddCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 25, -1, 20));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back_arrow.png"))); // NOI18N
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 25, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCustomersMouseClicked
        Design.panelChange(pnlContent, new CustomersAdd());
        btnAddCustomers.setVisible(false);
        btnBack.setVisible(true);
    }//GEN-LAST:event_btnAddCustomersMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        Design.panelChange(pnlContent, new CustomersMain(this.admin));
        btnAddCustomers.setVisible(true);
        btnBack.setVisible(false);
    }//GEN-LAST:event_btnBackMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel btnAddCustomers;
    private static javax.swing.JLabel btnBack;
    private static javax.swing.JLabel lblTitle;
    private static javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}
