/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.admin.container.content;

import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;

/**
 *
 * @author USER
 */
public class AdminSalesSearch extends javax.swing.JPanel {

    /**
     * Creates new form AdminSalesAdd
     */
    public AdminSalesSearch() {
        initComponents();
        jScrollPane1.getVerticalScrollBar().setPreferredSize( new Dimension(0,0) );
        jTable1.getTableHeader().setFont(new java.awt.Font("Roboto", Font.BOLD, 15));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new java.awt.Panel();
        fecha = new javax.swing.JLabel();
        cliente = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        ruc_nui = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        fecha_ = new javax.swing.JTextField();
        cliente_ = new javax.swing.JTextField();
        direccion_ = new javax.swing.JTextField();
        ruc_nui_ = new javax.swing.JTextField();
        telefono_ = new javax.swing.JTextField();
        total_ = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(236, 239, 244));
        setPreferredSize(new java.awt.Dimension(840, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContent.setBackground(new java.awt.Color(236, 239, 244));
        pnlContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fecha.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        fecha.setForeground(new java.awt.Color(59, 66, 82));
        fecha.setText("Fecha: ");
        pnlContent.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cliente.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        cliente.setForeground(new java.awt.Color(59, 66, 82));
        cliente.setText("Cliente: ");
        pnlContent.add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        direccion.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        direccion.setForeground(new java.awt.Color(59, 66, 82));
        direccion.setText("Dirección: ");
        pnlContent.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        ruc_nui.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        ruc_nui.setForeground(new java.awt.Color(59, 66, 82));
        ruc_nui.setText("RUC/NUI: ");
        pnlContent.add(ruc_nui, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        telefono.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        telefono.setForeground(new java.awt.Color(59, 66, 82));
        telefono.setText("Teléfono: ");
        pnlContent.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));

        total.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        total.setForeground(new java.awt.Color(59, 66, 82));
        total.setText("TOTAL:");
        pnlContent.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, -1, -1));

        jTable1.setBackground(new java.awt.Color(229, 233, 240));
        jTable1.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Descripción", "Precio Unitario", "IVA", "Descuento", "Subtotal"
            }
        ));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new java.awt.Color(129,161,193));

        pnlContent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 840, 310));

        fecha_.setBackground(new java.awt.Color(229, 233, 240));
        fecha_.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        fecha_.setBorder(null);
        fecha_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha_ActionPerformed(evt);
            }
        });
        pnlContent.add(fecha_, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 190, 22));

        cliente_.setBackground(new java.awt.Color(229, 233, 240));
        cliente_.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        cliente_.setBorder(null);
        cliente_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliente_ActionPerformed(evt);
            }
        });
        pnlContent.add(cliente_, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 190, 22));

        direccion_.setBackground(new java.awt.Color(229, 233, 240));
        direccion_.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        direccion_.setBorder(null);
        pnlContent.add(direccion_, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 190, 22));

        ruc_nui_.setBackground(new java.awt.Color(229, 233, 240));
        ruc_nui_.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        ruc_nui_.setBorder(null);
        pnlContent.add(ruc_nui_, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 190, 22));

        telefono_.setBackground(new java.awt.Color(229, 233, 240));
        telefono_.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        telefono_.setBorder(null);
        pnlContent.add(telefono_, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 190, 22));

        total_.setBackground(new java.awt.Color(236, 239, 244));
        total_.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        total_.setBorder(null);
        total_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_ActionPerformed(evt);
            }
        });
        pnlContent.add(total_, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 130, 22));

        add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 450));

        AddButton.setBackground(new java.awt.Color(180, 142, 173));
        AddButton.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        AddButton.setForeground(new java.awt.Color(76, 86, 106));
        AddButton.setText("IMPRIMIR");
        AddButton.setBorder(null);
        AddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void fecha_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha_ActionPerformed

    private void cliente_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliente_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cliente_ActionPerformed

    private void total_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel cliente;
    private javax.swing.JTextField cliente_;
    private javax.swing.JLabel direccion;
    private javax.swing.JTextField direccion_;
    private javax.swing.JLabel fecha;
    private javax.swing.JTextField fecha_;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Panel pnlContent;
    private javax.swing.JLabel ruc_nui;
    private javax.swing.JTextField ruc_nui_;
    private javax.swing.JLabel telefono;
    private javax.swing.JTextField telefono_;
    private javax.swing.JLabel total;
    private javax.swing.JTextField total_;
    // End of variables declaration//GEN-END:variables
}
