/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.admin.container.content;

/**
 *
 * @author JoaoJV
 */
public class AdminSuppliersAddSuppliers extends javax.swing.JPanel {

    /**
     * Creates new form AdminSuppliersAddSuppliers
     */
    public AdminSuppliersAddSuppliers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        nameTextField1 = new javax.swing.JTextField();
        phone = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        mailTextField2 = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        rucTextField3 = new javax.swing.JTextField();
        ruc = new javax.swing.JLabel();
        phoneTextField3 = new javax.swing.JTextField();
        mail = new javax.swing.JLabel();
        AddButtonSupplier = new javax.swing.JButton();

        setBackground(new java.awt.Color(236, 239, 244));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(229, 233, 240));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setBackground(new java.awt.Color(76, 86, 106));
        name.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        name.setForeground(new java.awt.Color(76, 86, 106));
        name.setText("Nombre:");
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        nameTextField1.setBackground(new java.awt.Color(236, 239, 244));
        nameTextField1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nameTextField1.setBorder(null);
        jPanel2.add(nameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 190, 22));

        phone.setBackground(new java.awt.Color(76, 86, 106));
        phone.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        phone.setForeground(new java.awt.Color(76, 86, 106));
        phone.setText("Teléfono:");
        jPanel2.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        addressTextField.setBackground(new java.awt.Color(236, 239, 244));
        addressTextField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        addressTextField.setBorder(null);
        jPanel2.add(addressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 190, 22));

        mailTextField2.setBackground(new java.awt.Color(236, 239, 244));
        mailTextField2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        mailTextField2.setBorder(null);
        jPanel2.add(mailTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 190, 22));

        address.setBackground(new java.awt.Color(76, 86, 106));
        address.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        address.setForeground(new java.awt.Color(76, 86, 106));
        address.setText("Dirección:");
        jPanel2.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        rucTextField3.setBackground(new java.awt.Color(236, 239, 244));
        rucTextField3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        rucTextField3.setBorder(null);
        jPanel2.add(rucTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 190, 22));

        ruc.setBackground(new java.awt.Color(76, 86, 106));
        ruc.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        ruc.setForeground(new java.awt.Color(76, 86, 106));
        ruc.setText("RUC:");
        jPanel2.add(ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        phoneTextField3.setBackground(new java.awt.Color(236, 239, 244));
        phoneTextField3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        phoneTextField3.setBorder(null);
        jPanel2.add(phoneTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 190, 22));

        mail.setBackground(new java.awt.Color(76, 86, 106));
        mail.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        mail.setForeground(new java.awt.Color(76, 86, 106));
        mail.setText("E-mail");
        jPanel2.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 440));

        AddButtonSupplier.setBackground(new java.awt.Color(143, 188, 187));
        AddButtonSupplier.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        AddButtonSupplier.setForeground(new java.awt.Color(76, 86, 106));
        AddButtonSupplier.setText("Agregar");
        AddButtonSupplier.setBorder(null);
        AddButtonSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(AddButtonSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 120, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButtonSupplier;
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mail;
    private javax.swing.JTextField mailTextField2;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameTextField1;
    private javax.swing.JLabel phone;
    private javax.swing.JTextField phoneTextField3;
    private javax.swing.JLabel ruc;
    private javax.swing.JTextField rucTextField3;
    // End of variables declaration//GEN-END:variables
}
