/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.main.content;

import com.logic.main.Functions;
import com.logic.model.Order;
import com.logic.model.Person;
import com.logic.views.CustomerView;
import com.logic.views.SellView;

import javax.swing.BorderFactory;

/**
 *
 * @author mrmango
 */
public class CustomersAdd extends javax.swing.JPanel {

    Integer idCustomer;
    CustomerView cmView = new CustomerView();
    SellView sellView = new SellView();
    Person employee;

    public CustomersAdd(Person employee) {
        this.employee = employee;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNui = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        lblNui = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        btnSearchNui = new javax.swing.JButton();
        btnSell = new javax.swing.JButton();

        setBackground(new java.awt.Color(236, 239, 244));
        setPreferredSize(new java.awt.Dimension(840, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNui.setBackground(new java.awt.Color(229, 233, 240));
        txtNui.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        txtNui.setForeground(new java.awt.Color(130, 147, 181));
        txtNui.setBorder(null);
        add(txtNui, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 190, 35));
        txtNui.setBorder(BorderFactory.createCompoundBorder(txtNui.getBorder(),BorderFactory.createEmptyBorder(7, 10, 7, 10)));

        txtName.setBackground(new java.awt.Color(229, 233, 240));
        txtName.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        txtName.setForeground(new java.awt.Color(130, 147, 181));
        txtName.setBorder(null);
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 190, 35));
        txtName.setBorder(BorderFactory.createCompoundBorder(txtName.getBorder(),BorderFactory.createEmptyBorder(7, 10, 7, 10)));

        lblName.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lblName.setForeground(new java.awt.Color(76, 86, 106));
        lblName.setText("Nombre:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, 35));

        txtLastName.setBackground(new java.awt.Color(229, 233, 240));
        txtLastName.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(130, 147, 181));
        txtLastName.setBorder(null);
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 190, 35));
        txtLastName.setBorder(BorderFactory.createCompoundBorder(txtLastName.getBorder(),BorderFactory.createEmptyBorder(7, 10, 7, 10)));

        lblLastName.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(76, 86, 106));
        lblLastName.setText("Apellido:");
        add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, 35));

        lblNui.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lblNui.setForeground(new java.awt.Color(76, 86, 106));
        lblNui.setText("NUI:");
        add(lblNui, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, 35));

        lblAddress.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(76, 86, 106));
        lblAddress.setText("Direccion:");
        add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, 35));

        txtAddress.setBackground(new java.awt.Color(229, 233, 240));
        txtAddress.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(130, 147, 181));
        txtAddress.setBorder(null);
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 190, 35));
        txtAddress.setBorder(BorderFactory.createCompoundBorder(txtAddress.getBorder(),BorderFactory.createEmptyBorder(7, 10, 7, 10)));

        txtPhone.setBackground(new java.awt.Color(229, 233, 240));
        txtPhone.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(130, 147, 181));
        txtPhone.setBorder(null);
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 190, 35));
        txtPhone.setBorder(BorderFactory.createCompoundBorder(txtPhone.getBorder(),BorderFactory.createEmptyBorder(7, 10, 7, 10)));

        lblPhone.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(76, 86, 106));
        lblPhone.setText("Telefono:");
        add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, 35));

        txtEmail.setBackground(new java.awt.Color(229, 233, 240));
        txtEmail.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(130, 147, 181));
        txtEmail.setBorder(null);
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 190, 35));
        txtEmail.setBorder(BorderFactory.createCompoundBorder(txtEmail.getBorder(),BorderFactory.createEmptyBorder(7, 10, 7, 10)));

        lblEmail.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(76, 86, 106));
        lblEmail.setText("Email:");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, 35));

        btnSearchNui.setBackground(new java.awt.Color(236, 239, 244));
        btnSearchNui.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btnSearchNui.setForeground(new java.awt.Color(67, 76, 94));
        btnSearchNui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        btnSearchNui.setBorder(null);
        btnSearchNui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchNui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNuiActionPerformed(evt);
            }
        });
        add(btnSearchNui, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 35, 35));

        btnSell.setBackground(new java.awt.Color(236, 239, 244));
        btnSell.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btnSell.setForeground(new java.awt.Color(67, 76, 94));
        btnSell.setText("Confirmar");
        btnSell.setBorder(null);
        btnSell.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });
        add(btnSell, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        if (idCustomer != null) {
            Order order = new Order();
            order.setIdEmployee(employee.getId());
            order.setIdCustomer(idCustomer);
            sellView.sellNewCustomer(order);
            Functions.clearJTextFields(this.getComponents());
        } else {
            Order order = new Order();
            order.setIdEmployee(employee.getId());
            cmView.addToDB(this);
            sellView.sellNewCustomer(order);
        }
    }//GEN-LAST:event_btnSellActionPerformed

    private void btnSearchNuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNuiActionPerformed
        String nui = txtNui.getText();
        idCustomer = cmView.searchCustomer(nui, this.getComponents());
    }//GEN-LAST:event_btnSearchNuiActionPerformed


    private javax.swing.JButton btnSearchNui;
    private javax.swing.JButton btnSell;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNui;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNui;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration                   
}
