/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.main.content;

import com.logic.views.CategoryView;
import com.logic.views.ProductView;
import com.logic.views.SupplierView;

import javax.swing.BorderFactory;

/**
 *
 * @author mrmango
 */
public class ProductsAdd extends javax.swing.JPanel {

    ProductView pdView = new ProductView();
    CategoryView ctView = new CategoryView();
    SupplierView spView = new SupplierView();

    public ProductsAdd() {
        initComponents();
        ctView.showQuery(bxCategory);
        spView.showQuery(bxSupplier);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblPvp = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        lvlPercent = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblSupplier = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtPvp = new javax.swing.JTextField();
        txtDiscount = new javax.swing.JTextField();
        bxCategory = new javax.swing.JComboBox<>();
        bxSupplier = new javax.swing.JComboBox<>();
        btnAddProduct = new javax.swing.JButton();

        setBackground(new java.awt.Color(236, 239, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContent.setBackground(new java.awt.Color(236, 239, 244));
        pnlContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setBackground(new java.awt.Color(76, 86, 106));
        lblName.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lblName.setForeground(new java.awt.Color(76, 86, 106));
        lblName.setText("Nombre:");
        pnlContent.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, 35));

        lblAmount.setBackground(new java.awt.Color(76, 86, 106));
        lblAmount.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lblAmount.setForeground(new java.awt.Color(76, 86, 106));
        lblAmount.setText("Cantidad:");
        pnlContent.add(lblAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, 35));

        lblPrice.setBackground(new java.awt.Color(76, 86, 106));
        lblPrice.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(76, 86, 106));
        lblPrice.setText("Precio:");
        pnlContent.add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 35));

        lblPvp.setBackground(new java.awt.Color(76, 86, 106));
        lblPvp.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lblPvp.setForeground(new java.awt.Color(76, 86, 106));
        lblPvp.setText("PVP:");
        pnlContent.add(lblPvp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, 35));

        lblDiscount.setBackground(new java.awt.Color(76, 86, 106));
        lblDiscount.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lblDiscount.setForeground(new java.awt.Color(76, 86, 106));
        lblDiscount.setText("Descuento:");
        pnlContent.add(lblDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, 35));

        lvlPercent.setBackground(new java.awt.Color(76, 86, 106));
        lvlPercent.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lvlPercent.setForeground(new java.awt.Color(76, 86, 106));
        lvlPercent.setText("%");
        pnlContent.add(lvlPercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, 35));

        lblCategory.setBackground(new java.awt.Color(76, 86, 106));
        lblCategory.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(76, 86, 106));
        lblCategory.setText("Categoria:");
        pnlContent.add(lblCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, 35));

        lblSupplier.setBackground(new java.awt.Color(76, 86, 106));
        lblSupplier.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lblSupplier.setForeground(new java.awt.Color(76, 86, 106));
        lblSupplier.setText("Supplier");
        pnlContent.add(lblSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, 35));

        txtName.setBackground(new java.awt.Color(229, 233, 240));
        txtName.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(130, 147, 181));
        txtName.setBorder(null);
        pnlContent.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 190, 35));
        txtName.setBorder(BorderFactory.createCompoundBorder(txtName.getBorder(),BorderFactory.createEmptyBorder(7, 10, 7, 10)));

        txtAmount.setBackground(new java.awt.Color(229, 233, 240));
        txtAmount.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtAmount.setForeground(new java.awt.Color(130, 147, 181));
        txtAmount.setBorder(null);
        pnlContent.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 190, 35));
        txtAmount.setBorder(BorderFactory.createCompoundBorder(txtAmount.getBorder(),BorderFactory.createEmptyBorder(7, 10, 7, 10)));

        txtPrice.setBackground(new java.awt.Color(229, 233, 240));
        txtPrice.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(130, 147, 181));
        txtPrice.setBorder(null);
        pnlContent.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 190, 35));
        txtPrice.setBorder(BorderFactory.createCompoundBorder(txtPrice.getBorder(),BorderFactory.createEmptyBorder(7, 10, 7, 10)));

        txtPvp.setBackground(new java.awt.Color(229, 233, 240));
        txtPvp.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtPvp.setForeground(new java.awt.Color(130, 147, 181));
        txtPvp.setBorder(null);
        pnlContent.add(txtPvp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 190, 35));
        txtPvp.setBorder(BorderFactory.createCompoundBorder(txtPvp.getBorder(),BorderFactory.createEmptyBorder(7, 10, 7, 10)));

        txtDiscount.setBackground(new java.awt.Color(229, 233, 240));
        txtDiscount.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtDiscount.setForeground(new java.awt.Color(130, 147, 181));
        txtDiscount.setBorder(null);
        pnlContent.add(txtDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 190, 35));
        txtDiscount.setBorder(BorderFactory.createCompoundBorder(txtDiscount.getBorder(),BorderFactory.createEmptyBorder(7, 10, 7, 10)));

        bxCategory.setBackground(new java.awt.Color(229, 233, 240));
        bxCategory.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        bxCategory.setForeground(new java.awt.Color(130, 147, 181));
        bxCategory.setBorder(null);
        pnlContent.add(bxCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 190, 35));

        bxSupplier.setBackground(new java.awt.Color(229, 233, 240));
        bxSupplier.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        bxSupplier.setForeground(new java.awt.Color(130, 147, 181));
        bxSupplier.setBorder(null);
        pnlContent.add(bxSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 190, 35));

        add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 480, 430));

        btnAddProduct.setBackground(new java.awt.Color(163, 190, 140));
        btnAddProduct.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btnAddProduct.setForeground(new java.awt.Color(76, 86, 106));
        btnAddProduct.setText("Agregar");
        btnAddProduct.setBorder(null);
        btnAddProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });
        add(btnAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        pdView.addToDB(pnlContent);

    }//GEN-LAST:event_btnAddProductActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JComboBox<String> bxCategory;
    private javax.swing.JComboBox<String> bxSupplier;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblPvp;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lvlPercent;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtPvp;
    // End of variables declaration//GEN-END:variables
}
