/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.main.content;

import com.logic.views.SupplierView;

import javax.swing.BorderFactory;

/**
 *
 * @author JoaoJV
 */
public class SuppliersAdd extends javax.swing.JPanel {

    SupplierView spView = new SupplierView();

    public SuppliersAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblRuc = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtRuc = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnAddSupplier = new javax.swing.JButton();

        setBackground(new java.awt.Color(236, 239, 244));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContent.setBackground(new java.awt.Color(236, 239, 244));
        pnlContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setBackground(new java.awt.Color(76, 86, 106));
        lblName.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lblName.setForeground(new java.awt.Color(76, 86, 106));
        lblName.setText("Nombre:");
        pnlContent.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 35));

        lblRuc.setBackground(new java.awt.Color(76, 86, 106));
        lblRuc.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lblRuc.setForeground(new java.awt.Color(76, 86, 106));
        lblRuc.setText("RUC:");
        pnlContent.add(lblRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 35));

        lblAddress.setBackground(new java.awt.Color(76, 86, 106));
        lblAddress.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(76, 86, 106));
        lblAddress.setText("Dirección:");
        pnlContent.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, 35));

        lblPhone.setBackground(new java.awt.Color(76, 86, 106));
        lblPhone.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(76, 86, 106));
        lblPhone.setText("Teléfono:");
        pnlContent.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, 35));

        lblEmail.setBackground(new java.awt.Color(76, 86, 106));
        lblEmail.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(76, 86, 106));
        lblEmail.setText("E-mail");
        pnlContent.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, 35));

        txtRuc.setBackground(new java.awt.Color(229, 233, 240));
        txtRuc.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtRuc.setForeground(new java.awt.Color(130, 147, 181));
        txtRuc.setBorder(null);
        pnlContent.add(txtRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 190, 35));
        txtRuc.setBorder(BorderFactory.createCompoundBorder(txtRuc.getBorder(),BorderFactory.createEmptyBorder(7, 10, 7, 10)));

        txtName.setBackground(new java.awt.Color(229, 233, 240));
        txtName.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(130, 147, 181));
        txtName.setBorder(null);
        pnlContent.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 190, 35));
        txtName.setBorder(BorderFactory.createCompoundBorder(txtName.getBorder(),BorderFactory.createEmptyBorder(7, 10, 7, 10)));

        txtAddress.setBackground(new java.awt.Color(229, 233, 240));
        txtAddress.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(130, 147, 181));
        txtAddress.setBorder(null);
        pnlContent.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 190, 35));
        txtAddress.setBorder(BorderFactory.createCompoundBorder(txtAddress.getBorder(),BorderFactory.createEmptyBorder(7, 10, 7, 10)));

        txtPhone.setBackground(new java.awt.Color(229, 233, 240));
        txtPhone.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(130, 147, 181));
        txtPhone.setBorder(null);
        pnlContent.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 190, 35));
        txtPhone.setBorder(BorderFactory.createCompoundBorder(txtPhone.getBorder(),BorderFactory.createEmptyBorder(7, 10, 7, 10)));

        txtEmail.setBackground(new java.awt.Color(229, 233, 240));
        txtEmail.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(130, 147, 181));
        txtEmail.setBorder(null);
        pnlContent.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 190, 35));
        txtEmail.setBorder(BorderFactory.createCompoundBorder(txtEmail.getBorder(),BorderFactory.createEmptyBorder(7, 10, 7, 10)));

        add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 460, 410));

        btnAddSupplier.setBackground(new java.awt.Color(163, 190, 140));
        btnAddSupplier.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btnAddSupplier.setForeground(new java.awt.Color(76, 86, 106));
        btnAddSupplier.setText("Agregar");
        btnAddSupplier.setBorder(null);
        btnAddSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSupplierActionPerformed(evt);
            }
        });
        add(btnAddSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplierActionPerformed
        spView.addToDB(pnlContent);
    }//GEN-LAST:event_btnAddSupplierActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSupplier;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRuc;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRuc;
    // End of variables declaration//GEN-END:variables
}
