/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dev.content;

/**
 *
 * @author mrmango
 */
public class AdminDashboardMain extends javax.swing.JPanel {

    /**
     * Creates new form AdminDashboardMain
     */
    public AdminDashboardMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSalesResume = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlCustomersResume = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 239, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSalesResume.setBackground(new java.awt.Color(229, 233, 240));
        pnlSalesResume.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(76, 86, 106));
        jLabel2.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(76, 86, 106));
        jLabel2.setText("Ventas de Hoy");
        pnlSalesResume.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        add(pnlSalesResume, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 360, 440));

        pnlCustomersResume.setBackground(new java.awt.Color(229, 233, 240));
        pnlCustomersResume.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(76, 86, 106));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(76, 86, 106));
        jLabel1.setText("Clientes Habituales");
        pnlCustomersResume.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        add(pnlCustomersResume, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 360, 440));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnlCustomersResume;
    private javax.swing.JPanel pnlSalesResume;
    // End of variables declaration//GEN-END:variables
}
